/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.Mongo;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Abrahan Barrios
 */
public class FrmUsuario extends javax.swing.JFrame {

    DB db; //definimos nuestra variable de base de datos.
    DBCollection tabla; //definimos nuestra variable de colección.

    String usuario;
    String contra;

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getContra() {
        return contra;
    }

    public void setContra(String contra) {
        this.contra = contra;
    }

    /**
     * Creates new form FrmUsuario
     */
    public FrmUsuario() {
        initComponents();
        try {
            Mongo mongo = new Mongo("localhost", 27017); //el puerto estandar es 27017
            db = mongo.getDB("registro");
            tabla = db.getCollection("usuario");

        } catch (UnknownHostException ex) {
            Logger.getLogger(FrmRegistroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGenPel = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lblEtiqueta2 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        txtSexo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblEtiqueta6 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        lblEtiqueta3 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        txtGenMus = new javax.swing.JTextField();
        lblEtiqueta = new javax.swing.JLabel();
        lblEtiqueta4 = new javax.swing.JLabel();
        lblEtiqueta1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDeTexto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombre.setEditable(false);

        lblEtiqueta2.setText("Sexo");

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Usuario");

        lblEtiqueta6.setText("Contrasenia");

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/actualizado.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        lblEtiqueta3.setText("Direccion");

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/anterior.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        lblEtiqueta.setText("Nombre");

        lblEtiqueta4.setText("Sucursal de Preferencia");

        lblEtiqueta1.setText("Edad");

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        areaDeTexto.setColumns(20);
        areaDeTexto.setRows(5);
        areaDeTexto.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                areaDeTextoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(areaDeTexto);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Datos Actuales");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnAtras)
                        .addGap(25, 25, 25)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEtiqueta3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGenMus, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEtiqueta4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGenPel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEtiqueta1)
                                    .addComponent(lblEtiqueta2))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEtiqueta)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEtiqueta6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEtiqueta)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEtiqueta1)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEtiqueta2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEtiqueta3)
                    .addComponent(txtGenMus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEtiqueta4)
                    .addComponent(txtGenPel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEtiqueta6)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnAtras)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEliminar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtEdad.setText("");
        txtSexo.setText("");
        txtGenMus.setText("");
        txtGenPel.setText("");
        txtContrasenia.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:

        BasicDBObject findTestItemQuery = new BasicDBObject();
        findTestItemQuery.put("nombre", "'" + txtNombre.getText() + "'");
        DBCursor testItemsCursor = tabla.find(findTestItemQuery);

        if (txtEdad.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Ingrese edad");
            txtEdad.requestFocus();
            return;
        }
        if (txtSexo.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Ingrese sexo");
            txtSexo.requestFocus();
            return;
        }
        if (txtGenMus.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Ingrese Generos Musicales");
            txtGenMus.requestFocus();
            return;
        }
        if (txtGenPel.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Ingrese Generos de Peliculas favoritas");
            txtGenPel.requestFocus();
            return;
        }

        if (txtContrasenia.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Ingrese contrasenia");
            txtContrasenia.requestFocus();
            return;
        }

        this.setContra(txtContrasenia.getText());
        if (testItemsCursor.hasNext()) {
            DBObject testCodeItem = testItemsCursor.next();
            testCodeItem.put("edad", Integer.parseInt(txtEdad.getText()));
            testCodeItem.put("sexo", "'" + txtSexo.getText() + "'");
            testCodeItem.put("direccion", "'" + txtGenMus.getText() + "'");
            testCodeItem.put("sucursal_preferencia", "'" + txtGenPel.getText() + "'");
            testCodeItem.put("contrasenia", "'" + txtContrasenia.getText() + "'");
            tabla.save(testCodeItem);

            JOptionPane.showMessageDialog(null, "Datos Actualizados");
            cargarInformacion();
        } else {
            JOptionPane.showMessageDialog(null, "Error,, no se pudieron actualizar los datos");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        if (txtContrasenia.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Ingrese contrasenia");
            txtContrasenia.requestFocus();
            return;
        }
        
        BasicDBObject deleteQuery = new BasicDBObject();
        deleteQuery.put("nombre", "'" + txtNombre.getText() + "'");
        deleteQuery.put("contrasenia", "'" + txtContrasenia.getText()+ "'");
        DBCursor cursor = tabla.find(deleteQuery);
        while (cursor.hasNext()) {
            DBObject item = cursor.next();
            tabla.remove(item);
            JOptionPane.showMessageDialog(null, "Usuario eliminado,usted saldra de Registro usuarios K.O");
            FrmInicioSesion inicio= new FrmInicioSesion();
            inicio.setVisible(true);
            this.dispose();
        }

        cargarInformacion();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void areaDeTextoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_areaDeTextoAncestorAdded
        // TODO add your handling code here:
        cargarInformacion();
    }//GEN-LAST:event_areaDeTextoAncestorAdded

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        FrmMuro muro= new FrmMuro();
        muro.setUsuario(usuario);
        muro.setContra(contra);
        muro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void cargarInformacion() {
        // TODO add your handling code here:

        BasicDBObject findTestItemQuery = new BasicDBObject();
        findTestItemQuery.put("nombre", "'" + usuario + "'");
        findTestItemQuery.put("contrasenia", "'" + contra + "'");
        DBCursor cursor = tabla.find(findTestItemQuery);

        txtNombre.setText(usuario);
        txtContrasenia.setText(contra);
        areaDeTexto.setText("");
        while (cursor.hasNext()) {
            areaDeTexto.setText(areaDeTexto.getText() + "\n" + cursor.next());
            /*
           aquí vamos a guardar lo que exista en nuestra area de texto, más un salto de línea " \n" y lo que se tenga en el cursor en ese momento.
           
             */
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDeTexto;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEtiqueta;
    private javax.swing.JLabel lblEtiqueta1;
    private javax.swing.JLabel lblEtiqueta2;
    private javax.swing.JLabel lblEtiqueta3;
    private javax.swing.JLabel lblEtiqueta4;
    private javax.swing.JLabel lblEtiqueta6;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtGenMus;
    private javax.swing.JTextField txtGenPel;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
